# 深度学习入门：sklearn中的神经网络

![image.png](./images/125.png)

![image.png](./images/126.png)

![image.png](./images/127.png)

![image.png](./images/128.png)

![image.png](./images/129.png)

![image.png](./images/130.png)

![image.png](./images/131.png)

![image.png](./images/132.png)

![image.png](./images/133.png)

![image.png](./images/134.png)

![image.png](./images/135.png)

![image.png](./images/136.png)

![image.png](./images/137.png)

![image.png](./images/138.png)

![image.png](./images/139.png)

In [8]:
#首先使用numpy来创建数据
import numpy as np

X = np.array([[0,0],[1,0],[0,1],[1,1]])
z_reg = np.array([-0.2,-0.05,-0.05,0.1])

In [9]:
X

array([[0, 0],
       [1, 0],
       [0, 1],
       [1, 1]])

In [10]:
X.shape

(4, 2)

In [11]:
z_reg

array([-0.2 , -0.05, -0.05,  0.1 ])

In [12]:
#定义实现简单线性回归的函数
def LinearR(x1,x2):
    w1,w2,b = 0.15,0.15,-0.2 #给定一组系数
    z = x1*w1 + x2*w2 + b
    return z

In [13]:
LinearR(X[:,0],X[:,1])

array([-0.2 , -0.05, -0.05,  0.1 ])

![image.png](./images/140.png)

![image.png](./images/141.png)

![image.png](./images/142.png)

![image.png](./images/143.png)

![image.png](./images/144.png)

In [16]:
#重新定义数据中的标签
y_and = [0,0,0,1]

#根据sigmoid公式定义sigmoid函数
def sigmoid(z):
    return 1/(1+np.exp(-z))

def AND_sigmoid(x1,x2): #带有sigmoid的与门
    w1,w2,b = 0.15,0.15,-0.2 #给定一组系数
    z = x1*w1 + x2*w2 + b
    o = sigmoid(z) #使用sigmoid函数将回归结果转换到（0,1）之间
    y = [int(x) for x in o >= 0.5] #根据阈值0.5，将（0,1）之间的概率转变为分类0和1
    return o,y

In [20]:
X

array([[0, 0],
       [1, 0],
       [0, 1],
       [1, 1]])

In [17]:
#o:sigmoid函数返回的概率结果
#y:对概率结果按阈值进行划分后，形成的0和1，也就是分类标签
o,y_sigm = AND_sigmoid(X[:,0],X[:,1])

In [18]:
o

array([0.450166  , 0.4875026 , 0.4875026 , 0.52497919])

In [19]:
y_sigm

[0, 0, 0, 1]

In [21]:
y_sigm == y_and

True

![image.png](./images/145.png)

![image.png](./images/146.png)

![image.png](./images/147.png)

![image.png](./images/148.png)

![image.png](./images/149.png)

![image.png](./images/150.png)

In [24]:
X

array([[0, 0],
       [1, 0],
       [0, 1],
       [1, 1]])

In [25]:
def AND(x1,x2): #与门函数
    w1,w2,b = 0.15,0.15,-0.23 #给定一组系数,和sigmoid相似
    z = x1*w1 + x2*w2 + b
    y = [int(x) for x in z >= 0]
    return y

In [26]:
AND(X[:,0],X[:,1])

[0, 0, 0, 1]

![image.png](./images/151.png)

![image.png](./images/152.png)

![image.png](./images/153.png)

![image.png](./images/154.png)

![image.png](./images/155.png)

![image.png](./images/156.png)

![image.png](./images/157.png)

![image.png](./images/158.png)

所以多分类时，还是按照以下来编号：

![image.png](./images/159.png)

![image.png](./images/160.png)

![image.png](./images/161.png)

![image.png](./images/162.png)

![image.png](./images/163.png)

会报错！！！

![image.png](./images/164.png)

![image.png](./images/165.png)

![image.png](./images/166.png)

![image.png](./images/167.png)

In [27]:
z = np.array([1010,1000,990])

In [28]:
c = np.max(z)
c

1010

In [29]:
#定义softmax函数
def softmax(z):
    c = np.max(z)
    exp_z = np.exp(z - c) #溢出对策
    sum_exp_z = np.sum(exp_z)
    o = exp_z / sum_exp_z
    return o

In [30]:
softmax(z)

array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])

In [31]:
sum(softmax(z))

1.0

![image.png](./images/168.png)

![image.png](./images/169.png)

![image.png](./images/170.png)

![image.png](./images/171.png)

![image.png](./images/172.png)

![image.png](./images/173.png)

![image.png](./images/174.png)